# These are supported funding model platforms

github: [] # Add GitHub Sponsors username(s)
patreon: # Add Patreon username
open_collective: # Add Open Collective project
ko_fi: # Add Ko-fi username
tidelift: # Add Tidelift package-manager/package-name
community_bridge: # Add Community Bridge project name
liberapay: # Add Liberapay username
issuehunt: # Add IssueHunt username
otechie: # Add Otechie username
lfx_crowdfunding: # Add LFX Crowdfunding project name
custom: [] # Add custom funding links
