name: 📚 Documentation Issue
description: Report an issue with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation!

  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues
          required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is affected?
      options:
        - README
        - API documentation
        - Code comments
        - Contributing guide
        - Security policy
        - Architecture documentation
        - Tutorial/Guide
        - Examples
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Error/Inaccuracy
        - Missing documentation
        - Unclear/Confusing
        - Outdated
        - Typo/Grammar
        - Enhancement suggestion
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue?
      placeholder: |
        File: README.md
        Section: Installation
        Line: 42
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: Describe the issue
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should it be improved?
      placeholder: Suggest better wording or additional content

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information

  - type: checkboxes
    id: volunteer
    attributes:
      label: Contribution
      options:
        - label: I would like to work on fixing this documentation issue
