name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have checked the project roadmap
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or use case
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your proposed solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions did you consider?
      placeholder: Describe alternative solutions or workarounds

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Enhancement to existing feature
        - Performance improvement
        - Developer experience improvement
        - Documentation improvement
        - Security enhancement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocking important use case)
        - High (important for many users)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a [user type], I want to [goal] so that [benefit]
        2. 
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: Who benefits from this feature and how?
      placeholder: |
        - Users affected:
        - Benefits:
        - Potential drawbacks:

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Considerations
      description: Any technical notes or implementation details to consider?
      placeholder: Architecture, dependencies, breaking changes, etc.

  - type: textarea
    id: security-privacy
    attributes:
      label: Security and Privacy Impact
      description: Any security or privacy implications?
      placeholder: Describe any security or privacy considerations

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Provide mockups, diagrams, or code examples if applicable
      placeholder: |
        ```rust
        // Example API or usage
        ```

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      options:
        - label: This feature maintains E2EE guarantees
        - label: This feature preserves user privacy
        - label: This feature is backward compatible (or breaking changes are acceptable)
        - label: This feature follows Rust best practices

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or links

  - type: checkboxes
    id: volunteer
    attributes:
      label: Contribution
      options:
        - label: I would like to work on implementing this feature
